apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: ibm-websphere-liberty
  namespace: {{ .Values.operatornamespace }}
spec:
  targetNamespaces:
  - {{ .Values.operatortargetnamespace }}
