# ibm-websphere-liberty-operator-subscription.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-websphere-liberty
  namespace: {{ .Values.operatornamespace }}
spec:
  installPlanApproval: {{ .Values.installplanapprovalconfig }}
  name: ibm-websphere-liberty
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
