# The OLM created csv objects on the cluster during install - there is a need to clean up csv created by the OLM, in addition to removing the subscription
# See https://olm.operatorframework.io/docs/tasks/uninstall-operator/#combine-steps-2-and-3 for context

apiVersion: batch/v1
kind: Job
metadata:
  name: wslo-uninstall-hook
  namespace: {{ .Values.operatornamespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "4"
    checkov.io/skip1: CKV_K8S_21
    checkov.io/skip2: CKV_K8S_30
    checkov.io/skip3: CKV_K8S_28
    checkov.io/skip4: CKV_K8S_22
    checkov.io/skip5: CKV_K8S_20
    checkov.io/skip6: CKV_K8S_37
    checkov.io/skip7: CKV_K8S_23
    checkov.io/skip8: CKV_K8S_38
    checkov.io/skip9: CKV_K8S_29
    checkov.io/skip10: CKV_K8S_40
    checkov.io/skip11: CKV_K8S_31
    checkov.io/skip12: CKV_K8S_9
    checkov.io/skip13: CKV_K8S_16
    checkov.io/skip14: CKV_K8S_8
    checkov.io/skip15: CKV_K8S_43
    checkov.io/skip16: CKV2_K8S_6
spec:
  template:
    metadata:
      name: wslo-uninstall-hook
    spec:
      restartPolicy: Never
      serviceAccountName: wslo-uninstall-hook-role-sa
      volumes:
        - name: scripts
          configMap:
            name: wslo-uninstall-scripts
            defaultMode: 0777
      containers:
      - name: wslo-uninstall-hook-job
        image: "icr.io/goldeneye_images/ubi9-cluster-tools:stable"
        # Deliberately always pull to grab latest image at the time when uninstall hook executed,
        # which may be a long time (multi months) after chart was deployed
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-xc", "/scripts/uninstall-operator-resources.sh {{ .Values.operatornamespace }}"]
        volumeMounts:
          - mountPath: /scripts
            name: scripts
            readOnly: true
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
