application:
  name: websphereliberty-app-sample
  namespace: samplelibertyapp
  image:
    path: "icr.io/appcafe/open-liberty/samples/getting-started"
    version: "latest@sha256:d735c2ceae5945a0f20adcbcb04e55472d2520b6d1abb6d3049c8521234d3b7a"
